using System.Diagnostics.CodeAnalysis;
using Content.Client.Guidebook.Controls;
using Content.Client.Guidebook.Richtext;
using Content.Client.Message;
using Content.Client.UserInterface.ControlExtensions;
using Content.Shared._TP.Kitchen;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._TP14.Guidebook.Controls;

/// <summary>
///     Control for embedding a deep-fryer recipe into a guidebook.
/// </summary>
[UsedImplicitly, GenerateTypedNameReferences]
public sealed partial class GuideDeepFryerEmbed : PanelContainer, IDocumentTag, ISearchableControl, IPrototypeRepresentationControl
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly ILogManager _logManager = default!;

    private readonly ISawmill _sawmill;

    public GuideDeepFryerEmbed()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        MouseFilter = MouseFilterMode.Stop;

        _sawmill = _logManager.GetSawmill("guidebook.deepfryer");
    }

    public GuideDeepFryerEmbed(string recipe) : this()
    {
        GenerateControl(_prototype.Index<DeepFryingRecipePrototype>(recipe));
    }

    private void GenerateControl(DeepFryingRecipePrototype recipe)
    {
        GenerateHeader(recipe);
        GenerateIngredients(recipe);
        GenerateCookTime(recipe);
    }

    private void GenerateCookTime(DeepFryingRecipePrototype recipe)
    {
        var msg = new FormattedMessage();
        msg.AddMarkupOrThrow(Loc.GetString("guidebook-deepfryer-cook-time", ("time", recipe.CookTime)));
        msg.Pop();

        CookTimeLabel.SetMessage(msg);
    }

    private void GenerateIngredients(DeepFryingRecipePrototype recipe)
    {
        var ingredient = _prototype.Index<EntityPrototype>(recipe.Ingredient);

        IngredientsGrid.AddChild(new GuideEntityEmbed(recipe.Ingredient, false, false));

        var nameMsg = new FormattedMessage();
        nameMsg.AddMarkupOrThrow(Loc.GetString("guidebook-deepfryer-ingredient-name", ("name", ingredient.Name)));
        nameMsg.Pop();

        var nameLabel = new GuidebookRichPrototypeLink();
        nameLabel.SetMessage(nameMsg);
        nameLabel.LinkedPrototype = ingredient;

        IngredientsGrid.AddChild(nameLabel);
    }

    private void GenerateHeader(DeepFryingRecipePrototype recipe)
    {
        var entity = _prototype.Index<EntityPrototype>(recipe.Result);
        RepresentedPrototype = entity;

        IconContainer.AddChild(new GuideEntityEmbed(recipe.Result, false, false));
        ResultName.SetMarkup(entity.Name);
        ResultDescription.SetMarkup(entity.Description);
    }

    public GuideDeepFryerEmbed(DeepFryingRecipePrototype recipe) : this()
    {
        GenerateControl(recipe);
    }

    public bool TryParseTag(Dictionary<string, string> args, [NotNullWhen(true)] out Control? control)
    {
        control = null;
        if (!args.TryGetValue("Recipe", out var id))
        {
            _sawmill.Error("Recipe embed tag is missing recipe prototype argument");
            return false;
        }

        if (!_prototype.TryIndex<DeepFryingRecipePrototype>(id, out var recipe))
        {
            _sawmill.Error($"Specified recipe prototype \"{id}\" is not a valid recipe prototype!");
            return false;
        }

        GenerateControl(recipe);
        control = this;
        return true;
    }

    public bool CheckMatchesSearch(string query)
    {
        return this.ChildrenContainText(query);
    }

    public void SetHiddenState(bool state, string query)
    {
        Visible = CheckMatchesSearch(query) ? state : !state;
    }

    public IPrototype? RepresentedPrototype { get; private set;  }
}
